import type { Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import "./globals.css";

// Importing Roboto with weights: 400 (regular), 600 (semi-bold), 700 (bold), and 800 (extra-bold)
const roboto = Roboto({
  weight: ["400", "600", "700", "800"],  // Regular, Semibold, Bold, Extra-bold
  variable: "--font-roboto",
  subsets: ["latin"],
});

// Importing Poppins with weights: 400 (regular), 600 (semi-bold), 700 (bold), and 800 (extra-bold)
const poppins = Poppins({
  weight: ["400", "600", "700", "800"],  // Regular, Semibold, Bold, Extra-bold
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nexa Developments LTD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} ${poppins.variable} antialiased`}>
      {children}
      </body>
    </html>
  );
}
